name: Docker Image Build

on:  
  push:
    branches: [ main, master ]

  workflow_dispatch:
    inputs:
      version:
        description: 'version of this branch'
        required: true
        type: string

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log into GitHub Container Registry
      run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build and push Docker image
      run: |
        PLATFORMS=linux/arm64,linux/amd64
        DOCKER_IMAGE=ghcr.io/herbertgao/sgcc_electricity_new
        ARCH_TAGS="arm64 amd64"        
        VERSION=${{ inputs.version || github.sha }}
        docker buildx build --build-arg VERSION=${VERSION} --platform $PLATFORMS -t $DOCKER_IMAGE:latest -t $DOCKER_IMAGE:${VERSION} --file Dockerfile-for-github-action --push .

        for ARCH in $ARCH_TAGS; do
          if [ "$ARCH" == "arm64" ]; then
            TAG_ARCH="aarch64"
          else
            TAG_ARCH=$ARCH
          fi
          docker buildx build --build-arg VERSION=${VERSION} --platform linux/${ARCH} -t ${DOCKER_IMAGE}-${TAG_ARCH}:latest -t ${DOCKER_IMAGE}-${TAG_ARCH}:${VERSION}  --file Dockerfile-for-github-action --push .
        done